services:
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter_datascience
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh
